Move DatabaseThread to its own file
I'm getting weird NoClassDefFoundError exceptions when reloading the
plugin after I recompiled it. Let's move out DatabaseThread to its own
file to see if that works, since it's the only class which is giving the
error for me.